import { Inter } from 'next/font/google';

import { App } from 'components/App';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
    return (
        <html lang="en">
            <body className={inter.className}>
                <App>{children}</App>
            </body>
        </html>
    );
}

export default RootLayout;
